# Generated by Django 3.2.18 on 2023-03-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20230304_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warden',
            old_name='name',
            new_name='address',
        ),
        migrations.AddField(
            model_name='warden',
            name='dependent_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='dependent_phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='dob',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='wardenId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='warden_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
