# Generated by Django 3.2.18 on 2023-03-05 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20230304_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='vacant',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='NewRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='newroom', to='management.room')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
