# Generated by Django 3.2.18 on 2023-03-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20230305_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
    ]
