# Generated by Django 3.2.18 on 2023-03-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_room_vacant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newregistration',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.student'),
        ),
    ]
