# Generated by Django 3.2.18 on 2023-03-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_feeregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='dues',
            new_name='is_approved',
        ),
    ]
