# Generated by Django 3.2.18 on 2023-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_studentleave_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='from_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='message',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentleave',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='to_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
