# Generated by Django 3.2.18 on 2023-03-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20230307_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.student'),
        ),
    ]
