# Generated by Django 3.2.18 on 2023-03-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_studentleave_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
