# Generated by Django 3.2.18 on 2023-03-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_studentleave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
