# Generated by Django 3.2.18 on 2023-03-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
