# Generated by Django 3.2.18 on 2023-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_checkout_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='is_accepted',
            field=models.IntegerField(default=0),
        ),
    ]
