# Generated by Django 3.2.18 on 2023-04-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_administration'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
